name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2
      
    - name: Install Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 2.0.0

    - name: Build release executable
      run: |
        nimble install -Y
        nimble build -d:release
        

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: binancedl-${{ matrix.os }}
        path: |
          binancedl
          README.md

