name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: stable

    - name: Build release executable
      run: |
        nimble build -d:release

    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: binancedl-${{ matrix.os }}
        path: |
          binancedl
          README.md

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload release assets
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: binancedl-${{ matrix.os }}
        asset_name: binancedl-${{ matrix.os }}
        asset_content_type: application/octet-stream
